float32 speed_kp
float32 speed_ki
float32 speed_kd
float32 angle_kp
float32 angle_ki
float32 angle_kd

float32 speed_filter_factor
float32 angle_filter_factor
float32 angular_velocity_factor

bool speed_regulator_enabled

---

bool success
string error_text
