float32 speed_filter_factor
float32 angle_filter_factor

bool lqr_enabled

bool pid_speed_regulator_enabled
float32 pid_angular_velocity_factor
float32 pid_speed_kp
float32 pid_speed_ki
float32 pid_speed_kd
float32 pid_angle_kp
float32 pid_angle_ki
float32 pid_angle_kd

float32 lqr_linear_velocity_k
float32 lqr_angular_velocity_k
float32 lqr_angle_k

---

bool success
string error_text
