# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RysRemoteMainWindowLayout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RysRemoteMainWindow(object):
	def setupUi(self, RysRemoteMainWindow):
		RysRemoteMainWindow.setObjectName("RysRemoteMainWindow")
		RysRemoteMainWindow.resize(713, 686)
		self.centralwidget = QtWidgets.QWidget(RysRemoteMainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.receivingGroupBox = QtWidgets.QGroupBox(self.centralwidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.receivingGroupBox.sizePolicy().hasHeightForWidth())
		self.receivingGroupBox.setSizePolicy(sizePolicy)
		self.receivingGroupBox.setObjectName("receivingGroupBox")
		self.horizontalLayout = QtWidgets.QHBoxLayout(self.receivingGroupBox)
		self.horizontalLayout.setContentsMargins(5, 0, 5, 5)
		self.horizontalLayout.setSpacing(5)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.rangeSensorsGroupBox = QtWidgets.QGroupBox(self.receivingGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.rangeSensorsGroupBox.sizePolicy().hasHeightForWidth())
		self.rangeSensorsGroupBox.setSizePolicy(sizePolicy)
		self.rangeSensorsGroupBox.setObjectName("rangeSensorsGroupBox")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.rangeSensorsGroupBox)
		self.verticalLayout.setContentsMargins(5, 5, 5, 5)
		self.verticalLayout.setSpacing(5)
		self.verticalLayout.setObjectName("verticalLayout")
		self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_8.setObjectName("horizontalLayout_8")
		self.rangeFrontLabel = QtWidgets.QLabel(self.rangeSensorsGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.rangeFrontLabel.sizePolicy().hasHeightForWidth())
		self.rangeFrontLabel.setSizePolicy(sizePolicy)
		self.rangeFrontLabel.setMinimumSize(QtCore.QSize(50, 20))
		self.rangeFrontLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.rangeFrontLabel.setObjectName("rangeFrontLabel")
		self.horizontalLayout_8.addWidget(self.rangeFrontLabel)
		self.rangeFrontBar = QtWidgets.QProgressBar(self.rangeSensorsGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.rangeFrontBar.sizePolicy().hasHeightForWidth())
		self.rangeFrontBar.setSizePolicy(sizePolicy)
		self.rangeFrontBar.setMinimumSize(QtCore.QSize(100, 0))
		self.rangeFrontBar.setMaximum(1500)
		self.rangeFrontBar.setProperty("value", 24)
		self.rangeFrontBar.setInvertedAppearance(False)
		self.rangeFrontBar.setObjectName("rangeFrontBar")
		self.horizontalLayout_8.addWidget(self.rangeFrontBar)
		self.verticalLayout.addLayout(self.horizontalLayout_8)
		self.line_5 = QtWidgets.QFrame(self.rangeSensorsGroupBox)
		self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
		self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_5.setObjectName("line_5")
		self.verticalLayout.addWidget(self.line_5)
		self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_11.setObjectName("horizontalLayout_11")
		self.rangeBackLabel = QtWidgets.QLabel(self.rangeSensorsGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.rangeBackLabel.sizePolicy().hasHeightForWidth())
		self.rangeBackLabel.setSizePolicy(sizePolicy)
		self.rangeBackLabel.setMinimumSize(QtCore.QSize(50, 20))
		self.rangeBackLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.rangeBackLabel.setObjectName("rangeBackLabel")
		self.horizontalLayout_11.addWidget(self.rangeBackLabel)
		self.rangeBackBar = QtWidgets.QProgressBar(self.rangeSensorsGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.rangeBackBar.sizePolicy().hasHeightForWidth())
		self.rangeBackBar.setSizePolicy(sizePolicy)
		self.rangeBackBar.setMinimumSize(QtCore.QSize(100, 0))
		self.rangeBackBar.setMaximum(1500)
		self.rangeBackBar.setProperty("value", 24)
		self.rangeBackBar.setInvertedAppearance(False)
		self.rangeBackBar.setObjectName("rangeBackBar")
		self.horizontalLayout_11.addWidget(self.rangeBackBar)
		self.verticalLayout.addLayout(self.horizontalLayout_11)
		self.line_4 = QtWidgets.QFrame(self.rangeSensorsGroupBox)
		self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
		self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_4.setObjectName("line_4")
		self.verticalLayout.addWidget(self.line_4)
		self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_9.setObjectName("horizontalLayout_9")
		self.rangeTopLabel = QtWidgets.QLabel(self.rangeSensorsGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.rangeTopLabel.sizePolicy().hasHeightForWidth())
		self.rangeTopLabel.setSizePolicy(sizePolicy)
		self.rangeTopLabel.setMinimumSize(QtCore.QSize(50, 20))
		self.rangeTopLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.rangeTopLabel.setObjectName("rangeTopLabel")
		self.horizontalLayout_9.addWidget(self.rangeTopLabel)
		self.rangeTopBar = QtWidgets.QProgressBar(self.rangeSensorsGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.rangeTopBar.sizePolicy().hasHeightForWidth())
		self.rangeTopBar.setSizePolicy(sizePolicy)
		self.rangeTopBar.setMinimumSize(QtCore.QSize(100, 0))
		self.rangeTopBar.setMaximum(1500)
		self.rangeTopBar.setProperty("value", 24)
		self.rangeTopBar.setInvertedAppearance(False)
		self.rangeTopBar.setObjectName("rangeTopBar")
		self.horizontalLayout_9.addWidget(self.rangeTopBar)
		self.verticalLayout.addLayout(self.horizontalLayout_9)
		self.line_12 = QtWidgets.QFrame(self.rangeSensorsGroupBox)
		self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
		self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_12.setObjectName("line_12")
		self.verticalLayout.addWidget(self.line_12)
		self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_10.setObjectName("horizontalLayout_10")
		self.rangeLeftLabel = QtWidgets.QLabel(self.rangeSensorsGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.rangeLeftLabel.sizePolicy().hasHeightForWidth())
		self.rangeLeftLabel.setSizePolicy(sizePolicy)
		self.rangeLeftLabel.setMinimumSize(QtCore.QSize(50, 20))
		self.rangeLeftLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.rangeLeftLabel.setObjectName("rangeLeftLabel")
		self.horizontalLayout_10.addWidget(self.rangeLeftLabel)
		self.rangeLeftBar = QtWidgets.QProgressBar(self.rangeSensorsGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.rangeLeftBar.sizePolicy().hasHeightForWidth())
		self.rangeLeftBar.setSizePolicy(sizePolicy)
		self.rangeLeftBar.setMinimumSize(QtCore.QSize(100, 0))
		self.rangeLeftBar.setMaximum(1500)
		self.rangeLeftBar.setProperty("value", 24)
		self.rangeLeftBar.setInvertedAppearance(False)
		self.rangeLeftBar.setObjectName("rangeLeftBar")
		self.horizontalLayout_10.addWidget(self.rangeLeftBar)
		self.verticalLayout.addLayout(self.horizontalLayout_10)
		self.line_16 = QtWidgets.QFrame(self.rangeSensorsGroupBox)
		self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
		self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_16.setObjectName("line_16")
		self.verticalLayout.addWidget(self.line_16)
		self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_12.setObjectName("horizontalLayout_12")
		self.rangeRightLabel = QtWidgets.QLabel(self.rangeSensorsGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.rangeRightLabel.sizePolicy().hasHeightForWidth())
		self.rangeRightLabel.setSizePolicy(sizePolicy)
		self.rangeRightLabel.setMinimumSize(QtCore.QSize(50, 20))
		self.rangeRightLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.rangeRightLabel.setObjectName("rangeRightLabel")
		self.horizontalLayout_12.addWidget(self.rangeRightLabel)
		self.rangeRightBar = QtWidgets.QProgressBar(self.rangeSensorsGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.rangeRightBar.sizePolicy().hasHeightForWidth())
		self.rangeRightBar.setSizePolicy(sizePolicy)
		self.rangeRightBar.setMinimumSize(QtCore.QSize(100, 0))
		self.rangeRightBar.setMaximum(1500)
		self.rangeRightBar.setProperty("value", 24)
		self.rangeRightBar.setInvertedAppearance(False)
		self.rangeRightBar.setObjectName("rangeRightBar")
		self.horizontalLayout_12.addWidget(self.rangeRightBar)
		self.verticalLayout.addLayout(self.horizontalLayout_12)
		self.horizontalLayout.addWidget(self.rangeSensorsGroupBox)
		self.batterySensorsGroupBox = QtWidgets.QGroupBox(self.receivingGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.batterySensorsGroupBox.sizePolicy().hasHeightForWidth())
		self.batterySensorsGroupBox.setSizePolicy(sizePolicy)
		self.batterySensorsGroupBox.setObjectName("batterySensorsGroupBox")
		self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.batterySensorsGroupBox)
		self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
		self.verticalLayout_4.setSpacing(5)
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_13.setObjectName("horizontalLayout_13")
		self.cell1Label = QtWidgets.QLabel(self.batterySensorsGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.cell1Label.sizePolicy().hasHeightForWidth())
		self.cell1Label.setSizePolicy(sizePolicy)
		self.cell1Label.setMinimumSize(QtCore.QSize(50, 20))
		self.cell1Label.setAlignment(QtCore.Qt.AlignCenter)
		self.cell1Label.setObjectName("cell1Label")
		self.horizontalLayout_13.addWidget(self.cell1Label)
		self.cell1Bar = QtWidgets.QProgressBar(self.batterySensorsGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.cell1Bar.sizePolicy().hasHeightForWidth())
		self.cell1Bar.setSizePolicy(sizePolicy)
		self.cell1Bar.setMinimumSize(QtCore.QSize(100, 0))
		self.cell1Bar.setMaximum(5000)
		self.cell1Bar.setProperty("value", 3500)
		self.cell1Bar.setInvertedAppearance(False)
		self.cell1Bar.setObjectName("cell1Bar")
		self.horizontalLayout_13.addWidget(self.cell1Bar)
		self.verticalLayout_4.addLayout(self.horizontalLayout_13)
		self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_14.setObjectName("horizontalLayout_14")
		self.cell2Label = QtWidgets.QLabel(self.batterySensorsGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.cell2Label.sizePolicy().hasHeightForWidth())
		self.cell2Label.setSizePolicy(sizePolicy)
		self.cell2Label.setMinimumSize(QtCore.QSize(50, 20))
		self.cell2Label.setAlignment(QtCore.Qt.AlignCenter)
		self.cell2Label.setObjectName("cell2Label")
		self.horizontalLayout_14.addWidget(self.cell2Label)
		self.cell2Bar = QtWidgets.QProgressBar(self.batterySensorsGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.cell2Bar.sizePolicy().hasHeightForWidth())
		self.cell2Bar.setSizePolicy(sizePolicy)
		self.cell2Bar.setMinimumSize(QtCore.QSize(100, 0))
		self.cell2Bar.setMaximum(5000)
		self.cell2Bar.setProperty("value", 3500)
		self.cell2Bar.setInvertedAppearance(False)
		self.cell2Bar.setObjectName("cell2Bar")
		self.horizontalLayout_14.addWidget(self.cell2Bar)
		self.verticalLayout_4.addLayout(self.horizontalLayout_14)
		self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_15.setObjectName("horizontalLayout_15")
		self.cell3Label = QtWidgets.QLabel(self.batterySensorsGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.cell3Label.sizePolicy().hasHeightForWidth())
		self.cell3Label.setSizePolicy(sizePolicy)
		self.cell3Label.setMinimumSize(QtCore.QSize(50, 20))
		self.cell3Label.setAlignment(QtCore.Qt.AlignCenter)
		self.cell3Label.setObjectName("cell3Label")
		self.horizontalLayout_15.addWidget(self.cell3Label)
		self.cell3Bar = QtWidgets.QProgressBar(self.batterySensorsGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.cell3Bar.sizePolicy().hasHeightForWidth())
		self.cell3Bar.setSizePolicy(sizePolicy)
		self.cell3Bar.setMinimumSize(QtCore.QSize(100, 0))
		self.cell3Bar.setMaximum(5000)
		self.cell3Bar.setProperty("value", 3500)
		self.cell3Bar.setInvertedAppearance(False)
		self.cell3Bar.setObjectName("cell3Bar")
		self.horizontalLayout_15.addWidget(self.cell3Bar)
		self.verticalLayout_4.addLayout(self.horizontalLayout_15)
		self.line_13 = QtWidgets.QFrame(self.batterySensorsGroupBox)
		self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
		self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_13.setObjectName("line_13")
		self.verticalLayout_4.addWidget(self.line_13)
		self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_16.setObjectName("horizontalLayout_16")
		self.temperatureLabel = QtWidgets.QLabel(self.batterySensorsGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.temperatureLabel.sizePolicy().hasHeightForWidth())
		self.temperatureLabel.setSizePolicy(sizePolicy)
		self.temperatureLabel.setMinimumSize(QtCore.QSize(50, 20))
		self.temperatureLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.temperatureLabel.setObjectName("temperatureLabel")
		self.horizontalLayout_16.addWidget(self.temperatureLabel)
		self.temperatureBar = QtWidgets.QProgressBar(self.batterySensorsGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.temperatureBar.sizePolicy().hasHeightForWidth())
		self.temperatureBar.setSizePolicy(sizePolicy)
		self.temperatureBar.setMinimumSize(QtCore.QSize(100, 0))
		self.temperatureBar.setMaximum(150)
		self.temperatureBar.setProperty("value", 25)
		self.temperatureBar.setInvertedAppearance(False)
		self.temperatureBar.setObjectName("temperatureBar")
		self.horizontalLayout_16.addWidget(self.temperatureBar)
		self.verticalLayout_4.addLayout(self.horizontalLayout_16)
		self.horizontalLayout.addWidget(self.batterySensorsGroupBox)
		self.imuGroupBox = QtWidgets.QGroupBox(self.receivingGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.imuGroupBox.sizePolicy().hasHeightForWidth())
		self.imuGroupBox.setSizePolicy(sizePolicy)
		self.imuGroupBox.setObjectName("imuGroupBox")
		self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.imuGroupBox)
		self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
		self.verticalLayout_3.setSpacing(5)
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.rollDial = QtWidgets.QDial(self.imuGroupBox)
		self.rollDial.setEnabled(False)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.rollDial.sizePolicy().hasHeightForWidth())
		self.rollDial.setSizePolicy(sizePolicy)
		self.rollDial.setMinimumSize(QtCore.QSize(80, 80))
		self.rollDial.setMinimum(-150)
		self.rollDial.setMaximum(150)
		self.rollDial.setProperty("value", -90)
		self.rollDial.setSliderPosition(-90)
		self.rollDial.setTracking(True)
		self.rollDial.setOrientation(QtCore.Qt.Horizontal)
		self.rollDial.setInvertedAppearance(False)
		self.rollDial.setInvertedControls(False)
		self.rollDial.setWrapping(False)
		self.rollDial.setNotchTarget(6.0)
		self.rollDial.setNotchesVisible(True)
		self.rollDial.setObjectName("rollDial")
		self.verticalLayout_3.addWidget(self.rollDial)
		self.rollValueLabel = QtWidgets.QLabel(self.imuGroupBox)
		self.rollValueLabel.setMinimumSize(QtCore.QSize(50, 0))
		self.rollValueLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.rollValueLabel.setObjectName("rollValueLabel")
		self.verticalLayout_3.addWidget(self.rollValueLabel)
		self.rotationXValueLabel = QtWidgets.QLabel(self.imuGroupBox)
		self.rotationXValueLabel.setMinimumSize(QtCore.QSize(50, 0))
		self.rotationXValueLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.rotationXValueLabel.setObjectName("rotationXValueLabel")
		self.verticalLayout_3.addWidget(self.rotationXValueLabel)
		self.horizontalLayout.addWidget(self.imuGroupBox)
		self.verticalLayout_2.addWidget(self.receivingGroupBox)
		self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		self.mapGroupBox = QtWidgets.QGroupBox(self.centralwidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.mapGroupBox.sizePolicy().hasHeightForWidth())
		self.mapGroupBox.setSizePolicy(sizePolicy)
		self.mapGroupBox.setObjectName("mapGroupBox")
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mapGroupBox)
		self.horizontalLayout_2.setContentsMargins(5, 0, 5, 5)
		self.horizontalLayout_2.setSpacing(5)
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.mapGraphicsView = QtWidgets.QGraphicsView(self.mapGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.mapGraphicsView.sizePolicy().hasHeightForWidth())
		self.mapGraphicsView.setSizePolicy(sizePolicy)
		self.mapGraphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
		self.mapGraphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
		self.mapGraphicsView.setOptimizationFlags(QtWidgets.QGraphicsView.DontAdjustForAntialiasing|QtWidgets.QGraphicsView.DontSavePainterState)
		self.mapGraphicsView.setObjectName("mapGraphicsView")
		self.horizontalLayout_2.addWidget(self.mapGraphicsView)
		self.mapSettingsVerticalLayout = QtWidgets.QVBoxLayout()
		self.mapSettingsVerticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
		self.mapSettingsVerticalLayout.setObjectName("mapSettingsVerticalLayout")
		self.positionCheckBox = QtWidgets.QCheckBox(self.mapGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.positionCheckBox.sizePolicy().hasHeightForWidth())
		self.positionCheckBox.setSizePolicy(sizePolicy)
		self.positionCheckBox.setChecked(True)
		self.positionCheckBox.setObjectName("positionCheckBox")
		self.mapSettingsVerticalLayout.addWidget(self.positionCheckBox)
		self.pathCheckBox = QtWidgets.QCheckBox(self.mapGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pathCheckBox.sizePolicy().hasHeightForWidth())
		self.pathCheckBox.setSizePolicy(sizePolicy)
		self.pathCheckBox.setChecked(True)
		self.pathCheckBox.setObjectName("pathCheckBox")
		self.mapSettingsVerticalLayout.addWidget(self.pathCheckBox)
		self.obstaclesCheckBox = QtWidgets.QCheckBox(self.mapGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.obstaclesCheckBox.sizePolicy().hasHeightForWidth())
		self.obstaclesCheckBox.setSizePolicy(sizePolicy)
		self.obstaclesCheckBox.setChecked(True)
		self.obstaclesCheckBox.setObjectName("obstaclesCheckBox")
		self.mapSettingsVerticalLayout.addWidget(self.obstaclesCheckBox)
		self.clearMapButton = QtWidgets.QPushButton(self.mapGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.clearMapButton.sizePolicy().hasHeightForWidth())
		self.clearMapButton.setSizePolicy(sizePolicy)
		self.clearMapButton.setObjectName("clearMapButton")
		self.mapSettingsVerticalLayout.addWidget(self.clearMapButton)
		self.horizontalLayout_2.addLayout(self.mapSettingsVerticalLayout)
		self.horizontalLayout_3.addWidget(self.mapGroupBox)
		self.steeringGroupBox = QtWidgets.QGroupBox(self.centralwidget)
		self.steeringGroupBox.setObjectName("steeringGroupBox")
		self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.steeringGroupBox)
		self.verticalLayout_6.setContentsMargins(5, 0, 5, 5)
		self.verticalLayout_6.setSpacing(5)
		self.verticalLayout_6.setObjectName("verticalLayout_6")
		self.line_2 = QtWidgets.QFrame(self.steeringGroupBox)
		self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_2.setObjectName("line_2")
		self.verticalLayout_6.addWidget(self.line_2)
		self.line = QtWidgets.QFrame(self.steeringGroupBox)
		self.line.setFrameShape(QtWidgets.QFrame.VLine)
		self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line.setObjectName("line")
		self.verticalLayout_6.addWidget(self.line)
		self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_5.setSpacing(6)
		self.horizontalLayout_5.setObjectName("horizontalLayout_5")
		self.axisVerticalLayout = QtWidgets.QVBoxLayout()
		self.axisVerticalLayout.setObjectName("axisVerticalLayout")
		self.gamepadXLabel = QtWidgets.QLabel(self.steeringGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.gamepadXLabel.sizePolicy().hasHeightForWidth())
		self.gamepadXLabel.setSizePolicy(sizePolicy)
		self.gamepadXLabel.setMinimumSize(QtCore.QSize(60, 25))
		self.gamepadXLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.gamepadXLabel.setObjectName("gamepadXLabel")
		self.axisVerticalLayout.addWidget(self.gamepadXLabel)
		self.gamepadYLabel = QtWidgets.QLabel(self.steeringGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.gamepadYLabel.sizePolicy().hasHeightForWidth())
		self.gamepadYLabel.setSizePolicy(sizePolicy)
		self.gamepadYLabel.setMinimumSize(QtCore.QSize(60, 25))
		self.gamepadYLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.gamepadYLabel.setObjectName("gamepadYLabel")
		self.axisVerticalLayout.addWidget(self.gamepadYLabel)
		self.gamepadHorizontalLayout = QtWidgets.QHBoxLayout()
		self.gamepadHorizontalLayout.setObjectName("gamepadHorizontalLayout")
		self.gamepadComboBoxLabel = QtWidgets.QLabel(self.steeringGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.gamepadComboBoxLabel.sizePolicy().hasHeightForWidth())
		self.gamepadComboBoxLabel.setSizePolicy(sizePolicy)
		self.gamepadComboBoxLabel.setMinimumSize(QtCore.QSize(60, 25))
		self.gamepadComboBoxLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.gamepadComboBoxLabel.setObjectName("gamepadComboBoxLabel")
		self.gamepadHorizontalLayout.addWidget(self.gamepadComboBoxLabel)
		self.gamepadComboBox = QtWidgets.QComboBox(self.steeringGroupBox)
		self.gamepadComboBox.setEnabled(False)
		self.gamepadComboBox.setMinimumSize(QtCore.QSize(70, 25))
		self.gamepadComboBox.setObjectName("gamepadComboBox")
		self.gamepadComboBox.addItem("")
		self.gamepadHorizontalLayout.addWidget(self.gamepadComboBox)
		self.axisVerticalLayout.addLayout(self.gamepadHorizontalLayout)
		self.throttleHorizontalLayout = QtWidgets.QHBoxLayout()
		self.throttleHorizontalLayout.setObjectName("throttleHorizontalLayout")
		self.throttleComboBoxLabel = QtWidgets.QLabel(self.steeringGroupBox)
		self.throttleComboBoxLabel.setMinimumSize(QtCore.QSize(60, 25))
		self.throttleComboBoxLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.throttleComboBoxLabel.setObjectName("throttleComboBoxLabel")
		self.throttleHorizontalLayout.addWidget(self.throttleComboBoxLabel)
		self.throttleComboBox = QtWidgets.QComboBox(self.steeringGroupBox)
		self.throttleComboBox.setEnabled(False)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.throttleComboBox.sizePolicy().hasHeightForWidth())
		self.throttleComboBox.setSizePolicy(sizePolicy)
		self.throttleComboBox.setMinimumSize(QtCore.QSize(70, 25))
		self.throttleComboBox.setObjectName("throttleComboBox")
		self.throttleComboBox.addItem("")
		self.throttleComboBox.setItemText(0, "[none]")
		self.throttleComboBox.addItem("")
		self.throttleComboBox.addItem("")
		self.throttleComboBox.addItem("")
		self.throttleComboBox.addItem("")
		self.throttleComboBox.addItem("")
		self.throttleHorizontalLayout.addWidget(self.throttleComboBox)
		self.axisVerticalLayout.addLayout(self.throttleHorizontalLayout)
		self.rotationHorizontalLayout = QtWidgets.QHBoxLayout()
		self.rotationHorizontalLayout.setObjectName("rotationHorizontalLayout")
		self.rotationComboBoxLabel = QtWidgets.QLabel(self.steeringGroupBox)
		self.rotationComboBoxLabel.setMinimumSize(QtCore.QSize(60, 25))
		self.rotationComboBoxLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.rotationComboBoxLabel.setObjectName("rotationComboBoxLabel")
		self.rotationHorizontalLayout.addWidget(self.rotationComboBoxLabel)
		self.rotationComboBox = QtWidgets.QComboBox(self.steeringGroupBox)
		self.rotationComboBox.setEnabled(False)
		self.rotationComboBox.setMinimumSize(QtCore.QSize(70, 25))
		self.rotationComboBox.setObjectName("rotationComboBox")
		self.rotationComboBox.addItem("")
		self.rotationComboBox.setItemText(0, "[none]")
		self.rotationComboBox.addItem("")
		self.rotationComboBox.addItem("")
		self.rotationComboBox.addItem("")
		self.rotationComboBox.addItem("")
		self.rotationComboBox.addItem("")
		self.rotationHorizontalLayout.addWidget(self.rotationComboBox)
		self.axisVerticalLayout.addLayout(self.rotationHorizontalLayout)
		self.multiplierHorizontalLayout = QtWidgets.QHBoxLayout()
		self.multiplierHorizontalLayout.setObjectName("multiplierHorizontalLayout")
		self.multiplierComboBoxLabel = QtWidgets.QLabel(self.steeringGroupBox)
		self.multiplierComboBoxLabel.setMinimumSize(QtCore.QSize(60, 25))
		self.multiplierComboBoxLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.multiplierComboBoxLabel.setObjectName("multiplierComboBoxLabel")
		self.multiplierHorizontalLayout.addWidget(self.multiplierComboBoxLabel)
		self.multiplierDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.steeringGroupBox)
		self.multiplierDoubleSpinBox.setMinimumSize(QtCore.QSize(70, 25))
		self.multiplierDoubleSpinBox.setMinimum(-1.0)
		self.multiplierDoubleSpinBox.setMaximum(1.0)
		self.multiplierDoubleSpinBox.setSingleStep(0.1)
		self.multiplierDoubleSpinBox.setProperty("value", 1.0)
		self.multiplierDoubleSpinBox.setObjectName("multiplierDoubleSpinBox")
		self.multiplierHorizontalLayout.addWidget(self.multiplierDoubleSpinBox)
		self.axisVerticalLayout.addLayout(self.multiplierHorizontalLayout)
		self.reverseThrottleCheckBox = QtWidgets.QCheckBox(self.steeringGroupBox)
		self.reverseThrottleCheckBox.setObjectName("reverseThrottleCheckBox")
		self.axisVerticalLayout.addWidget(self.reverseThrottleCheckBox)
		self.horizontalLayout_5.addLayout(self.axisVerticalLayout)
		self.line_3 = QtWidgets.QFrame(self.steeringGroupBox)
		self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_3.setObjectName("line_3")
		self.horizontalLayout_5.addWidget(self.line_3)
		self.verticalLayout_5 = QtWidgets.QVBoxLayout()
		self.verticalLayout_5.setObjectName("verticalLayout_5")
		self.balancingEnabledCheckBox = QtWidgets.QCheckBox(self.steeringGroupBox)
		self.balancingEnabledCheckBox.setMinimumSize(QtCore.QSize(0, 25))
		self.balancingEnabledCheckBox.setChecked(False)
		self.balancingEnabledCheckBox.setObjectName("balancingEnabledCheckBox")
		self.verticalLayout_5.addWidget(self.balancingEnabledCheckBox)
		self.precisionHorizontalLayout = QtWidgets.QHBoxLayout()
		self.precisionHorizontalLayout.setObjectName("precisionHorizontalLayout")
		self.precisionComboBoxLabel = QtWidgets.QLabel(self.steeringGroupBox)
		self.precisionComboBoxLabel.setMinimumSize(QtCore.QSize(60, 25))
		self.precisionComboBoxLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.precisionComboBoxLabel.setObjectName("precisionComboBoxLabel")
		self.precisionHorizontalLayout.addWidget(self.precisionComboBoxLabel)
		self.precisionSpinBox = QtWidgets.QSpinBox(self.steeringGroupBox)
		self.precisionSpinBox.setMinimumSize(QtCore.QSize(70, 25))
		self.precisionSpinBox.setMinimum(1)
		self.precisionSpinBox.setMaximum(32)
		self.precisionSpinBox.setObjectName("precisionSpinBox")
		self.precisionHorizontalLayout.addWidget(self.precisionSpinBox)
		self.verticalLayout_5.addLayout(self.precisionHorizontalLayout)
		self.regulatorSettingsButton = QtWidgets.QPushButton(self.steeringGroupBox)
		self.regulatorSettingsButton.setObjectName("regulatorSettingsButton")
		self.verticalLayout_5.addWidget(self.regulatorSettingsButton)
		self.horizontalLayout_5.addLayout(self.verticalLayout_5)
		self.verticalLayout_6.addLayout(self.horizontalLayout_5)
		spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.verticalLayout_6.addItem(spacerItem)
		self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		self.steeringGraphicsView = QtWidgets.QGraphicsView(self.steeringGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.steeringGraphicsView.sizePolicy().hasHeightForWidth())
		self.steeringGraphicsView.setSizePolicy(sizePolicy)
		self.steeringGraphicsView.setMinimumSize(QtCore.QSize(150, 150))
		self.steeringGraphicsView.setSizeIncrement(QtCore.QSize(10, 10))
		self.steeringGraphicsView.setBaseSize(QtCore.QSize(200, 200))
		self.steeringGraphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
		self.steeringGraphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
		self.steeringGraphicsView.setOptimizationFlags(QtWidgets.QGraphicsView.DontAdjustForAntialiasing|QtWidgets.QGraphicsView.DontSavePainterState)
		self.steeringGraphicsView.setObjectName("steeringGraphicsView")
		self.horizontalLayout_4.addWidget(self.steeringGraphicsView)
		self.enableButton = QtWidgets.QPushButton(self.steeringGroupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.enableButton.sizePolicy().hasHeightForWidth())
		self.enableButton.setSizePolicy(sizePolicy)
		self.enableButton.setMinimumSize(QtCore.QSize(150, 150))
		self.enableButton.setSizeIncrement(QtCore.QSize(10, 10))
		self.enableButton.setAutoFillBackground(False)
		self.enableButton.setStyleSheet("background-color: green;")
		self.enableButton.setFlat(False)
		self.enableButton.setObjectName("enableButton")
		self.horizontalLayout_4.addWidget(self.enableButton)
		self.verticalLayout_6.addLayout(self.horizontalLayout_4)
		self.horizontalLayout_3.addWidget(self.steeringGroupBox)
		self.verticalLayout_2.addLayout(self.horizontalLayout_3)
		RysRemoteMainWindow.setCentralWidget(self.centralwidget)

		self.retranslateUi(RysRemoteMainWindow)
		QtCore.QMetaObject.connectSlotsByName(RysRemoteMainWindow)

	def retranslateUi(self, RysRemoteMainWindow):
		_translate = QtCore.QCoreApplication.translate
		RysRemoteMainWindow.setWindowTitle(_translate("RysRemoteMainWindow", "RysRemote"))
		self.receivingGroupBox.setTitle(_translate("RysRemoteMainWindow", "Receiving"))
		self.rangeSensorsGroupBox.setTitle(_translate("RysRemoteMainWindow", "Range sensors"))
		self.rangeFrontLabel.setText(_translate("RysRemoteMainWindow", "Front"))
		self.rangeFrontBar.setFormat(_translate("RysRemoteMainWindow", "%v"))
		self.rangeBackLabel.setText(_translate("RysRemoteMainWindow", "Back"))
		self.rangeBackBar.setFormat(_translate("RysRemoteMainWindow", "%v"))
		self.rangeTopLabel.setText(_translate("RysRemoteMainWindow", "Top"))
		self.rangeTopBar.setFormat(_translate("RysRemoteMainWindow", "%v"))
		self.rangeLeftLabel.setText(_translate("RysRemoteMainWindow", "Left"))
		self.rangeLeftBar.setFormat(_translate("RysRemoteMainWindow", "%v"))
		self.rangeRightLabel.setText(_translate("RysRemoteMainWindow", "Right"))
		self.rangeRightBar.setFormat(_translate("RysRemoteMainWindow", "%v"))
		self.batterySensorsGroupBox.setTitle(_translate("RysRemoteMainWindow", "Battery & Temperature"))
		self.cell1Label.setText(_translate("RysRemoteMainWindow", "Cell 1"))
		self.cell1Bar.setFormat(_translate("RysRemoteMainWindow", "%vmV"))
		self.cell2Label.setText(_translate("RysRemoteMainWindow", "Cell 2"))
		self.cell2Bar.setFormat(_translate("RysRemoteMainWindow", "%vmV"))
		self.cell3Label.setText(_translate("RysRemoteMainWindow", "Cell 3"))
		self.cell3Bar.setFormat(_translate("RysRemoteMainWindow", "%vmV"))
		self.temperatureLabel.setText(_translate("RysRemoteMainWindow", "Temp"))
		self.temperatureBar.setFormat(_translate("RysRemoteMainWindow", "%v°C"))
		self.imuGroupBox.setTitle(_translate("RysRemoteMainWindow", "IMU"))
		self.rollValueLabel.setText(_translate("RysRemoteMainWindow", "    Roll: -90.0000"))
		self.rotationXValueLabel.setText(_translate("RysRemoteMainWindow", "Rotation: 0.0000"))
		self.mapGroupBox.setTitle(_translate("RysRemoteMainWindow", "Map"))
		self.positionCheckBox.setText(_translate("RysRemoteMainWindow", "Position"))
		self.pathCheckBox.setText(_translate("RysRemoteMainWindow", "Path"))
		self.obstaclesCheckBox.setText(_translate("RysRemoteMainWindow", "Obstacles"))
		self.clearMapButton.setText(_translate("RysRemoteMainWindow", "Clear map"))
		self.steeringGroupBox.setTitle(_translate("RysRemoteMainWindow", "Steering"))
		self.gamepadXLabel.setText(_translate("RysRemoteMainWindow", "X: 0.0000"))
		self.gamepadYLabel.setText(_translate("RysRemoteMainWindow", "Y: 0.0000"))
		self.gamepadComboBoxLabel.setText(_translate("RysRemoteMainWindow", "Gamepad"))
		self.gamepadComboBox.setItemText(0, _translate("RysRemoteMainWindow", "[none]"))
		self.throttleComboBoxLabel.setText(_translate("RysRemoteMainWindow", "Throttle"))
		self.throttleComboBox.setItemText(1, _translate("RysRemoteMainWindow", "0"))
		self.throttleComboBox.setItemText(2, _translate("RysRemoteMainWindow", "1"))
		self.throttleComboBox.setItemText(3, _translate("RysRemoteMainWindow", "2"))
		self.throttleComboBox.setItemText(4, _translate("RysRemoteMainWindow", "3"))
		self.throttleComboBox.setItemText(5, _translate("RysRemoteMainWindow", "4"))
		self.rotationComboBoxLabel.setText(_translate("RysRemoteMainWindow", "Rotation"))
		self.rotationComboBox.setItemText(1, _translate("RysRemoteMainWindow", "0"))
		self.rotationComboBox.setItemText(2, _translate("RysRemoteMainWindow", "1"))
		self.rotationComboBox.setItemText(3, _translate("RysRemoteMainWindow", "2"))
		self.rotationComboBox.setItemText(4, _translate("RysRemoteMainWindow", "3"))
		self.rotationComboBox.setItemText(5, _translate("RysRemoteMainWindow", "4"))
		self.multiplierComboBoxLabel.setText(_translate("RysRemoteMainWindow", "Multiplier"))
		self.reverseThrottleCheckBox.setText(_translate("RysRemoteMainWindow", "Reverse Throttle"))
		self.balancingEnabledCheckBox.setText(_translate("RysRemoteMainWindow", "Balancing"))
		self.precisionComboBoxLabel.setText(_translate("RysRemoteMainWindow", "Precision"))
		self.regulatorSettingsButton.setText(_translate("RysRemoteMainWindow", "Regulator settings"))
		self.enableButton.setText(_translate("RysRemoteMainWindow", "Enable"))


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	RysRemoteMainWindow = QtWidgets.QMainWindow()
	ui = Ui_RysRemoteMainWindow()
	ui.setupUi(RysRemoteMainWindow)
	RysRemoteMainWindow.show()
	sys.exit(app.exec_())

