# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RysRemoteMainWindowLayout.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RysRemoteMainWindow(object):
    def setupUi(self, RysRemoteMainWindow):
        RysRemoteMainWindow.setObjectName("RysRemoteMainWindow")
        RysRemoteMainWindow.resize(678, 520)
        self.centralwidget = QtWidgets.QWidget(RysRemoteMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.receivingGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.receivingGroupBox.setObjectName("receivingGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.receivingGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sonarVerticalLayout = QtWidgets.QVBoxLayout()
        self.sonarVerticalLayout.setObjectName("sonarVerticalLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.sonarFrontLabel = QtWidgets.QLabel(self.receivingGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sonarFrontLabel.sizePolicy().hasHeightForWidth())
        self.sonarFrontLabel.setSizePolicy(sizePolicy)
        self.sonarFrontLabel.setMinimumSize(QtCore.QSize(50, 50))
        self.sonarFrontLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sonarFrontLabel.setObjectName("sonarFrontLabel")
        self.horizontalLayout_8.addWidget(self.sonarFrontLabel)
        self.sonarFrontBar = QtWidgets.QProgressBar(self.receivingGroupBox)
        self.sonarFrontBar.setMinimumSize(QtCore.QSize(100, 0))
        self.sonarFrontBar.setMaximum(800)
        self.sonarFrontBar.setProperty("value", 24)
        self.sonarFrontBar.setInvertedAppearance(False)
        self.sonarFrontBar.setObjectName("sonarFrontBar")
        self.horizontalLayout_8.addWidget(self.sonarFrontBar)
        self.sonarVerticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.sonarBackLabel = QtWidgets.QLabel(self.receivingGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sonarBackLabel.sizePolicy().hasHeightForWidth())
        self.sonarBackLabel.setSizePolicy(sizePolicy)
        self.sonarBackLabel.setMinimumSize(QtCore.QSize(50, 50))
        self.sonarBackLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sonarBackLabel.setObjectName("sonarBackLabel")
        self.horizontalLayout_11.addWidget(self.sonarBackLabel)
        self.sonarBackBar = QtWidgets.QProgressBar(self.receivingGroupBox)
        self.sonarBackBar.setMinimumSize(QtCore.QSize(100, 0))
        self.sonarBackBar.setMaximum(800)
        self.sonarBackBar.setProperty("value", 24)
        self.sonarBackBar.setInvertedAppearance(False)
        self.sonarBackBar.setObjectName("sonarBackBar")
        self.horizontalLayout_11.addWidget(self.sonarBackBar)
        self.sonarVerticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.sonarTopLabel = QtWidgets.QLabel(self.receivingGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sonarTopLabel.sizePolicy().hasHeightForWidth())
        self.sonarTopLabel.setSizePolicy(sizePolicy)
        self.sonarTopLabel.setMinimumSize(QtCore.QSize(50, 50))
        self.sonarTopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sonarTopLabel.setObjectName("sonarTopLabel")
        self.horizontalLayout_9.addWidget(self.sonarTopLabel)
        self.sonarTopBar = QtWidgets.QProgressBar(self.receivingGroupBox)
        self.sonarTopBar.setMinimumSize(QtCore.QSize(100, 0))
        self.sonarTopBar.setMaximum(800)
        self.sonarTopBar.setProperty("value", 24)
        self.sonarTopBar.setInvertedAppearance(False)
        self.sonarTopBar.setObjectName("sonarTopBar")
        self.horizontalLayout_9.addWidget(self.sonarTopBar)
        self.sonarVerticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout.addLayout(self.sonarVerticalLayout)
        self.imuVerticalLayout = QtWidgets.QVBoxLayout()
        self.imuVerticalLayout.setObjectName("imuVerticalLayout")
        self.imuCalibrateButton = QtWidgets.QPushButton(self.receivingGroupBox)
        self.imuCalibrateButton.setObjectName("imuCalibrateButton")
        self.imuVerticalLayout.addWidget(self.imuCalibrateButton)
        self.rollDial = QtWidgets.QDial(self.receivingGroupBox)
        self.rollDial.setEnabled(False)
        self.rollDial.setMinimumSize(QtCore.QSize(150, 150))
        self.rollDial.setMinimum(-150)
        self.rollDial.setMaximum(150)
        self.rollDial.setProperty("value", -90)
        self.rollDial.setSliderPosition(-90)
        self.rollDial.setTracking(True)
        self.rollDial.setOrientation(QtCore.Qt.Horizontal)
        self.rollDial.setInvertedAppearance(False)
        self.rollDial.setInvertedControls(False)
        self.rollDial.setWrapping(False)
        self.rollDial.setNotchTarget(6.0)
        self.rollDial.setNotchesVisible(True)
        self.rollDial.setObjectName("rollDial")
        self.imuVerticalLayout.addWidget(self.rollDial)
        self.rollValueLabel = QtWidgets.QLabel(self.receivingGroupBox)
        self.rollValueLabel.setMinimumSize(QtCore.QSize(50, 30))
        self.rollValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rollValueLabel.setObjectName("rollValueLabel")
        self.imuVerticalLayout.addWidget(self.rollValueLabel)
        self.rollLabel = QtWidgets.QLabel(self.receivingGroupBox)
        self.rollLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.rollLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rollLabel.setObjectName("rollLabel")
        self.imuVerticalLayout.addWidget(self.rollLabel)
        self.horizontalLayout.addLayout(self.imuVerticalLayout)
        self.verticalLayout_2.addWidget(self.receivingGroupBox)
        self.sendinggroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.sendinggroupBox.setObjectName("sendinggroupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.sendinggroupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.enableButton = QtWidgets.QPushButton(self.sendinggroupBox)
        self.enableButton.setMinimumSize(QtCore.QSize(100, 100))
        self.enableButton.setAutoFillBackground(False)
        self.enableButton.setStyleSheet("background-color: green;")
        self.enableButton.setFlat(False)
        self.enableButton.setObjectName("enableButton")
        self.horizontalLayout_4.addWidget(self.enableButton)
        self.steeringVerticalLayout = QtWidgets.QVBoxLayout()
        self.steeringVerticalLayout.setObjectName("steeringVerticalLayout")
        self.steeringGraphicsView = QtWidgets.QGraphicsView(self.sendinggroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.steeringGraphicsView.sizePolicy().hasHeightForWidth())
        self.steeringGraphicsView.setSizePolicy(sizePolicy)
        self.steeringGraphicsView.setMinimumSize(QtCore.QSize(150, 150))
        self.steeringGraphicsView.setSizeIncrement(QtCore.QSize(20, 20))
        self.steeringGraphicsView.setBaseSize(QtCore.QSize(200, 200))
        self.steeringGraphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.steeringGraphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.steeringGraphicsView.setOptimizationFlags(QtWidgets.QGraphicsView.DontAdjustForAntialiasing|QtWidgets.QGraphicsView.DontSavePainterState)
        self.steeringGraphicsView.setObjectName("steeringGraphicsView")
        self.steeringVerticalLayout.addWidget(self.steeringGraphicsView)
        self.steeringLabel = QtWidgets.QLabel(self.sendinggroupBox)
        self.steeringLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.steeringLabel.setObjectName("steeringLabel")
        self.steeringVerticalLayout.addWidget(self.steeringLabel)
        self.horizontalLayout_4.addLayout(self.steeringVerticalLayout)
        self.axisVerticalLayout = QtWidgets.QVBoxLayout()
        self.axisVerticalLayout.setObjectName("axisVerticalLayout")
        self.gamepadHorizontalLayout = QtWidgets.QHBoxLayout()
        self.gamepadHorizontalLayout.setObjectName("gamepadHorizontalLayout")
        self.gamepadComboBoxLabel = QtWidgets.QLabel(self.sendinggroupBox)
        self.gamepadComboBoxLabel.setMinimumSize(QtCore.QSize(60, 50))
        self.gamepadComboBoxLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gamepadComboBoxLabel.setObjectName("gamepadComboBoxLabel")
        self.gamepadHorizontalLayout.addWidget(self.gamepadComboBoxLabel)
        self.gamepadComboBox = QtWidgets.QComboBox(self.sendinggroupBox)
        self.gamepadComboBox.setEnabled(False)
        self.gamepadComboBox.setMinimumSize(QtCore.QSize(70, 30))
        self.gamepadComboBox.setObjectName("gamepadComboBox")
        self.gamepadComboBox.addItem("")
        self.gamepadHorizontalLayout.addWidget(self.gamepadComboBox)
        self.axisVerticalLayout.addLayout(self.gamepadHorizontalLayout)
        self.throttleHorizontalLayout = QtWidgets.QHBoxLayout()
        self.throttleHorizontalLayout.setObjectName("throttleHorizontalLayout")
        self.throttleComboBoxLabel = QtWidgets.QLabel(self.sendinggroupBox)
        self.throttleComboBoxLabel.setMinimumSize(QtCore.QSize(60, 50))
        self.throttleComboBoxLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.throttleComboBoxLabel.setObjectName("throttleComboBoxLabel")
        self.throttleHorizontalLayout.addWidget(self.throttleComboBoxLabel)
        self.throttleComboBox = QtWidgets.QComboBox(self.sendinggroupBox)
        self.throttleComboBox.setEnabled(False)
        self.throttleComboBox.setMinimumSize(QtCore.QSize(70, 30))
        self.throttleComboBox.setObjectName("throttleComboBox")
        self.throttleComboBox.addItem("")
        self.throttleComboBox.setItemText(0, "[none]")
        self.throttleComboBox.addItem("")
        self.throttleComboBox.addItem("")
        self.throttleComboBox.addItem("")
        self.throttleComboBox.addItem("")
        self.throttleComboBox.addItem("")
        self.throttleHorizontalLayout.addWidget(self.throttleComboBox)
        self.axisVerticalLayout.addLayout(self.throttleHorizontalLayout)
        self.rotationHorizontalLayout = QtWidgets.QHBoxLayout()
        self.rotationHorizontalLayout.setObjectName("rotationHorizontalLayout")
        self.rotationComboBoxLabel = QtWidgets.QLabel(self.sendinggroupBox)
        self.rotationComboBoxLabel.setMinimumSize(QtCore.QSize(60, 50))
        self.rotationComboBoxLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rotationComboBoxLabel.setObjectName("rotationComboBoxLabel")
        self.rotationHorizontalLayout.addWidget(self.rotationComboBoxLabel)
        self.rotationComboBox = QtWidgets.QComboBox(self.sendinggroupBox)
        self.rotationComboBox.setEnabled(False)
        self.rotationComboBox.setMinimumSize(QtCore.QSize(70, 30))
        self.rotationComboBox.setObjectName("rotationComboBox")
        self.rotationComboBox.addItem("")
        self.rotationComboBox.setItemText(0, "[none]")
        self.rotationComboBox.addItem("")
        self.rotationComboBox.addItem("")
        self.rotationComboBox.addItem("")
        self.rotationComboBox.addItem("")
        self.rotationComboBox.addItem("")
        self.rotationHorizontalLayout.addWidget(self.rotationComboBox)
        self.axisVerticalLayout.addLayout(self.rotationHorizontalLayout)
        self.horizontalLayout_4.addLayout(self.axisVerticalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.speedPIDLabel = QtWidgets.QLabel(self.sendinggroupBox)
        self.speedPIDLabel.setMinimumSize(QtCore.QSize(100, 30))
        self.speedPIDLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.speedPIDLabel.setObjectName("speedPIDLabel")
        self.verticalLayout.addWidget(self.speedPIDLabel)
        self.speedPIDHorizontalLayout = QtWidgets.QHBoxLayout()
        self.speedPIDHorizontalLayout.setObjectName("speedPIDHorizontalLayout")
        self.speedPSpinBox = QtWidgets.QDoubleSpinBox(self.sendinggroupBox)
        self.speedPSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.speedPSpinBox.setDecimals(4)
        self.speedPSpinBox.setProperty("value", 0.03)
        self.speedPSpinBox.setObjectName("speedPSpinBox")
        self.speedPIDHorizontalLayout.addWidget(self.speedPSpinBox)
        self.speedISpinBox = QtWidgets.QDoubleSpinBox(self.sendinggroupBox)
        self.speedISpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.speedISpinBox.setDecimals(4)
        self.speedISpinBox.setProperty("value", 0.0001)
        self.speedISpinBox.setObjectName("speedISpinBox")
        self.speedPIDHorizontalLayout.addWidget(self.speedISpinBox)
        self.speedDSpinBox = QtWidgets.QDoubleSpinBox(self.sendinggroupBox)
        self.speedDSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.speedDSpinBox.setDecimals(4)
        self.speedDSpinBox.setProperty("value", 0.008)
        self.speedDSpinBox.setObjectName("speedDSpinBox")
        self.speedPIDHorizontalLayout.addWidget(self.speedDSpinBox)
        self.verticalLayout.addLayout(self.speedPIDHorizontalLayout)
        self.anglePIDLabel = QtWidgets.QLabel(self.sendinggroupBox)
        self.anglePIDLabel.setMinimumSize(QtCore.QSize(100, 30))
        self.anglePIDLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.anglePIDLabel.setObjectName("anglePIDLabel")
        self.verticalLayout.addWidget(self.anglePIDLabel)
        self.anglePIDHorizontalLayout = QtWidgets.QHBoxLayout()
        self.anglePIDHorizontalLayout.setObjectName("anglePIDHorizontalLayout")
        self.anglePSpinBox = QtWidgets.QDoubleSpinBox(self.sendinggroupBox)
        self.anglePSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.anglePSpinBox.setDecimals(3)
        self.anglePSpinBox.setProperty("value", 50.0)
        self.anglePSpinBox.setObjectName("anglePSpinBox")
        self.anglePIDHorizontalLayout.addWidget(self.anglePSpinBox)
        self.angleISpinBox = QtWidgets.QDoubleSpinBox(self.sendinggroupBox)
        self.angleISpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.angleISpinBox.setDecimals(3)
        self.angleISpinBox.setProperty("value", 0.05)
        self.angleISpinBox.setObjectName("angleISpinBox")
        self.anglePIDHorizontalLayout.addWidget(self.angleISpinBox)
        self.angleDSpinBox = QtWidgets.QDoubleSpinBox(self.sendinggroupBox)
        self.angleDSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.angleDSpinBox.setDecimals(3)
        self.angleDSpinBox.setProperty("value", 20.0)
        self.angleDSpinBox.setObjectName("angleDSpinBox")
        self.anglePIDHorizontalLayout.addWidget(self.angleDSpinBox)
        self.verticalLayout.addLayout(self.anglePIDHorizontalLayout)
        self.setPIDsButton = QtWidgets.QPushButton(self.sendinggroupBox)
        self.setPIDsButton.setObjectName("setPIDsButton")
        self.verticalLayout.addWidget(self.setPIDsButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.sendinggroupBox)
        RysRemoteMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RysRemoteMainWindow)
        QtCore.QMetaObject.connectSlotsByName(RysRemoteMainWindow)

    def retranslateUi(self, RysRemoteMainWindow):
        _translate = QtCore.QCoreApplication.translate
        RysRemoteMainWindow.setWindowTitle(_translate("RysRemoteMainWindow", "RysRemote"))
        self.receivingGroupBox.setTitle(_translate("RysRemoteMainWindow", "Receiving"))
        self.sonarFrontLabel.setText(_translate("RysRemoteMainWindow", "Front"))
        self.sonarFrontBar.setFormat(_translate("RysRemoteMainWindow", "%v"))
        self.sonarBackLabel.setText(_translate("RysRemoteMainWindow", "Back"))
        self.sonarBackBar.setFormat(_translate("RysRemoteMainWindow", "%v"))
        self.sonarTopLabel.setText(_translate("RysRemoteMainWindow", "Top"))
        self.sonarTopBar.setFormat(_translate("RysRemoteMainWindow", "%v"))
        self.imuCalibrateButton.setText(_translate("RysRemoteMainWindow", "Calibrate IMU"))
        self.rollValueLabel.setText(_translate("RysRemoteMainWindow", "-90.0"))
        self.rollLabel.setText(_translate("RysRemoteMainWindow", "Roll"))
        self.sendinggroupBox.setTitle(_translate("RysRemoteMainWindow", "Sending"))
        self.enableButton.setText(_translate("RysRemoteMainWindow", "Enable"))
        self.steeringLabel.setText(_translate("RysRemoteMainWindow", "Steering"))
        self.gamepadComboBoxLabel.setText(_translate("RysRemoteMainWindow", "Gamepad"))
        self.gamepadComboBox.setItemText(0, _translate("RysRemoteMainWindow", "[none]"))
        self.throttleComboBoxLabel.setText(_translate("RysRemoteMainWindow", "Throttle"))
        self.throttleComboBox.setItemText(1, _translate("RysRemoteMainWindow", "0"))
        self.throttleComboBox.setItemText(2, _translate("RysRemoteMainWindow", "1"))
        self.throttleComboBox.setItemText(3, _translate("RysRemoteMainWindow", "2"))
        self.throttleComboBox.setItemText(4, _translate("RysRemoteMainWindow", "3"))
        self.throttleComboBox.setItemText(5, _translate("RysRemoteMainWindow", "4"))
        self.rotationComboBoxLabel.setText(_translate("RysRemoteMainWindow", "Rotation"))
        self.rotationComboBox.setItemText(1, _translate("RysRemoteMainWindow", "0"))
        self.rotationComboBox.setItemText(2, _translate("RysRemoteMainWindow", "1"))
        self.rotationComboBox.setItemText(3, _translate("RysRemoteMainWindow", "2"))
        self.rotationComboBox.setItemText(4, _translate("RysRemoteMainWindow", "3"))
        self.rotationComboBox.setItemText(5, _translate("RysRemoteMainWindow", "4"))
        self.speedPIDLabel.setText(_translate("RysRemoteMainWindow", "Speed PID (speed -> angle)"))
        self.anglePIDLabel.setText(_translate("RysRemoteMainWindow", "Angle PID (angle -> output)"))
        self.setPIDsButton.setText(_translate("RysRemoteMainWindow", "Set PID parameters"))

